# bashrc  
# On Mac OS X, link to this as bash_profile because
# Mac loads bash_profile on login. Unix loads bashrc on login.
#
# ln -s ~/bin/dotfiles/bash/bashrc ~/.bash_profile


# Display greeting on login

echo ""
echo -n "Unix on Mac OS X. Logged in as "; whoami
echo ""
echo -n "Today is "; date "+%d %B %Y %R %z"
echo ""
cal

# User specific environment and startup programs
echo -n "Uptime: "; uptime
##
# Paul Irish dotfiles for setting up work environment
# source: paulirish/dotfiles - GitHub
# Includes adaptations for Lewy MacBook
# Component: .bash_profile (set up basics)
##
# Load ~/.extra, ~/.bash_prompt, ~/.exports, ~/.aliases and ~/.functions
# ~/.extra can be used for settings you don’t want to commit
#CHANGED to add bash_ prefix to files that didn't already have it (prompt)
#for file in ~/.bash_{extra,prompt,exports,aliases,alias,functions}; do
#	[ -r "$file" ] && source "$file"
#done
#unset file

# Lewy's simplified startup
source ~/bin/dotfiles/bash/.bash_functions
source ~/bin/dotfiles/bash/bash_extra
source ~/bin/dotfiles/bash/bash_alias
source ~/bin/dotfiles/bash/bash_exports
source ~/bin/dotfiles/bash/bash_prompt




# init z   https://github.com/rupa/z
. ~/code/z/z.sh

# init rvm
#TODO consider rvm = Ruby Version Manager. (Not installed)
#source ~/.rvm/scripts/rvm

# Case-insensitive globbing (used in pathname expansion)
shopt -s nocaseglob

# Prefer US English and use UTF-8
export LC_ALL="en_US.UTF-8"
export LANG="en_US"

# Add tab completion for SSH hostnames based on ~/.ssh/config, ignoring wildcards
[ -e "$HOME/.ssh/config" ] && complete -o "default" -o "nospace" -W "$(grep "^Host" ~/.ssh/config | grep -v "[?*]" | cut -d " " -f2)" scp sftp ssh

# Add tab completion for `defaults read|write NSGlobalDomain`
# You could just use `-g` instead, but I like being explicit
complete -W "NSGlobalDomain" defaults
